import asyncio
import re

from mcstatus import JavaServer, BedrockServer

from astrbot.api.event import filter, AstrMessageEvent
from astrbot.api.star import Context, Star
from astrbot.api import logger
from astrbot.api.t2i import render_template
from astrbot.api.message import MessageChain, Image, Plain

DEFAULT_JE_PORT = 25565
DEFAULT_BE_PORT = 19132

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Noto Sans SC', 'Microsoft YaHei', sans-serif;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
    min-height: 100vh;
    display: flex; align-items: center; justify-content: center;
  }
  .card {
    width: 720px;
    background: rgba(255,255,255,0.06);
    border: 1px solid rgba(255,255,255,0.12);
    border-radius: 20px;
    padding: 40px;
    backdrop-filter: blur(20px);
    box-shadow: 0 20px 60px rgba(0,0,0,0.5);
  }
  .header {
    text-align: center;
    margin-bottom: 32px;
  }
  .header .icon {
    font-size: 48px;
    margin-bottom: 8px;
  }
  .header h1 {
    color: #e94560;
    font-size: 24px;
    font-weight: 700;
    letter-spacing: 2px;
  }
  .server-addr {
    text-align: center;
    color: #a0aec0;
    font-size: 14px;
    margin-bottom: 28px;
    padding: 10px 20px;
    background: rgba(233,69,96,0.1);
    border-radius: 10px;
    display: inline-block;
    width: 100%;
    word-break: break-all;
  }
  .grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin-bottom: 24px;
  }
  .stat {
    background: rgba(255,255,255,0.05);
    border-radius: 14px;
    padding: 20px;
    border: 1px solid rgba(255,255,255,0.08);
    transition: transform 0.2s;
  }
  .stat:hover { transform: translateY(-2px); }
  .stat .label {
    font-size: 12px;
    color: #718096;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 8px;
  }
  .stat .value {
    font-size: 22px;
    font-weight: 700;
    color: #e2e8f0;
  }
  .stat.full {
    grid-column: 1 / -1;
  }
  .motd-box {
    background: rgba(0,0,0,0.3);
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 14px;
    padding: 20px;
    margin-bottom: 24px;
  }
  .motd-box .label {
    font-size: 12px;
    color: #718096;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 10px;
  }
  .motd-box .content {
    font-size: 16px;
    color: #cbd5e0;
    line-height: 1.6;
  }
  .players-bar {
    height: 8px;
    background: rgba(255,255,255,0.1);
    border-radius: 4px;
    overflow: hidden;
    margin-top: 10px;
  }
  .players-fill {
    height: 100%;
    border-radius: 4px;
    background: linear-gradient(90deg, #e94560, #f5a623);
    transition: width 0.5s;
  }
  .footer {
    text-align: center;
    color: #4a5568;
    font-size: 11px;
    margin-top: 8px;
  }
  .edition-badge {
    display: inline-block;
    padding: 4px 12px;
    border-radius: 6px;
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 1px;
  }
  .edition-je { background: rgba(66,153,225,0.2); color: #63b3ed; }
  .edition-be { background: rgba(72,187,120,0.2); color: #68d391; }
  .online { color: #68d391; }
  .offline { color: #fc8181; }
  .latency-good { color: #68d391; }
  .latency-ok { color: #f6e05e; }
  .latency-bad { color: #fc8181; }
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <div class="icon">{{ "⛏️" }}</div>
    <h1>MINECRAFT SERVER</h1>
  </div>

  <div class="server-addr">
    {{ host }}:{{ port }}
  </div>

  <div class="grid">
    <div class="stat">
      <div class="label">版本</div>
      <div class="value" style="font-size:16px;">
        <span class="edition-badge {{ 'edition-je' if edition == 'je' else 'edition-be' }}">{{ 'JAVA' if edition == 'je' else 'BEDROCK' }}</span>
        <span style="margin-left:6px;color:#e2e8f0;">{{ version }}</span>
      </div>
    </div>

    <div class="stat">
      <div class="label">延迟</div>
      <div class="value">
        <span class="{{ latency_class }}">{{ '%.1f'|format(latency) }} ms</span>
      </div>
    </div>

    <div class="stat full">
      <div class="label">在线玩家</div>
      <div class="value">{{ players_online }} / {{ players_max }}</div>
      <div class="players-bar">
        <div class="players-fill" style="width:{{ players_percent }}%;"></div>
      </div>
    </div>
  </div>

  <div class="motd-box">
    <div class="label">MOTD</div>
    <div class="content">{{ motd }}</div>
  </div>

  <div class="footer">
    Generated by AstrBot MC Plugin &bull; {{ edition.upper() }} Edition
  </div>
</div>
</body>
</html>"""


class MCMotdPlugin(Star):
    def __init__(self, context: Context):
        super().__init__(context)

    @filter.command("motd")
    async def motd(self, event: AstrMessageEvent):
        '''查询Minecraft服务器MOTD信息。用法: /motd <服务器IP>:<端口> <je/be>，默认JE端口25565，BE端口19132'''
        raw = event.message_str.strip()
        parts = raw.split()
        if parts and parts[0] in ("/motd", "motd"):
            parts = parts[1:]

        if not parts:
            yield event.plain_result(
                "使用方法:\n"
                "/motd <服务器IP>[:端口] <je/be>\n\n"
                "示例:\n"
                "/motd mc.hypixel.net je\n"
                "/motd play.example.com:25565\n"
                "/motd 127.0.0.1 be\n\n"
                "默认端口: Java版 25565  |  基岩版 19132"
            )
            return

        server_addr = parts[0]
        edition = parts[1].lower() if len(parts) >= 2 else "je"

        if edition not in ("je", "be"):
            yield event.plain_result("版本参数错误，请使用 je (Java版) 或 be (基岩版)")
            return

        host, port = self._parse_address(server_addr, edition)
        if host is None:
            yield event.plain_result("端口号格式错误，请输入数字端口")
            return

        logger.info(f"查询Minecraft服务器 {host}:{port} ({'Java' if edition == 'je' else 'Bedrock'})")

        try:
            data = await self._query_server(host, port, edition)
            image_bytes = await render_template(HTML_TEMPLATE, data)
            chain = MessageChain([Image(data=image_bytes)])
            yield event.result(chain)
        except asyncio.TimeoutError:
            yield event.plain_result(f"查询超时: {host}:{port} 无响应，请检查地址是否正确或服务器是否在线")
        except OSError as e:
            yield event.plain_result(f"网络错误: 无法连接到 {host}:{port}\n{self._friendly_error(e)}")
        except Exception as e:
            logger.error(f"查询服务器异常 {host}:{port}: {e}", exc_info=True)
            yield event.plain_result(f"查询失败 {host}:{port}: {str(e)}")

    def _parse_address(self, server_addr: str, edition: str):
        if server_addr.startswith("["):
            m = re.match(r'\[(.+?)\]:(\d+)$', server_addr)
            if m:
                return m.group(1), int(m.group(2))
            return server_addr.strip("[]"), (DEFAULT_JE_PORT if edition == "je" else DEFAULT_BE_PORT)

        colon_count = server_addr.count(":")
        if colon_count >= 2:
            return server_addr, (DEFAULT_JE_PORT if edition == "je" else DEFAULT_BE_PORT)

        if colon_count == 1:
            host, port_str = server_addr.rsplit(":", 1)
            try:
                return host, int(port_str)
            except ValueError:
                return None, 0

        return server_addr, (DEFAULT_JE_PORT if edition == "je" else DEFAULT_BE_PORT)

    async def _query_server(self, host: str, port: int, edition: str) -> dict:
        loop = asyncio.get_running_loop()

        if edition == "je":
            status = await loop.run_in_executor(
                None, lambda: JavaServer(host, port).status()
            )
        else:
            status = await loop.run_in_executor(
                None, lambda: BedrockServer(host, port).status()
            )

        motd = self._format_motd(status.description)
        latency = round(status.latency, 1)
        version_name = status.version.name
        online = status.players.online
        max_players = status.players.max
        percent = min(100, round(online / max(max_players, 1) * 100, 1))

        if latency < 60:
            latency_class = "latency-good"
        elif latency < 150:
            latency_class = "latency-ok"
        else:
            latency_class = "latency-bad"

        return {
            "host": host,
            "port": port,
            "edition": edition,
            "version": version_name,
            "motd": motd,
            "latency": latency,
            "latency_class": latency_class,
            "players_online": online,
            "players_max": max_players,
            "players_percent": percent,
        }

    @staticmethod
    def _format_motd(description) -> str:
        if isinstance(description, str):
            return MCMotdPlugin._strip_color_codes(description.strip())
        if isinstance(description, dict):
            text = MCMotdPlugin._parse_text_component(description)
            return MCMotdPlugin._strip_color_codes(text)
        return str(description)

    @staticmethod
    def _parse_text_component(component) -> str:
        if isinstance(component, str):
            return component
        if isinstance(component, dict):
            text = component.get("text", "")
            for extra_item in component.get("extra", []):
                text += MCMotdPlugin._parse_text_component(extra_item)
            return text
        if isinstance(component, list):
            return "".join(MCMotdPlugin._parse_text_component(c) for c in component)
        return str(component)

    @staticmethod
    def _strip_color_codes(text: str) -> str:
        return re.sub(r'[\u00a7\u00A7][0-9a-fA-Fk-oK-OrR]', '', text)

    @staticmethod
    def _friendly_error(exc: OSError) -> str:
        msg = str(exc).lower()
        if "refused" in msg:
            return "连接被拒绝，请检查端口是否正确"
        if "timed out" in msg or "timeout" in msg:
            return "连接超时，服务器可能不在线"
        if "no address" in msg or "getaddrinfo" in msg or "name resolution" in msg:
            return "无法解析服务器地址，请检查IP/域名是否正确"
        return str(exc)

    async def terminate(self):
        pass
